### ISSUE TITLE
/src/jobs/* directory missing from installation

### ISSUE THREAD

**Issue by xeon65** [cronkeep/cronkeep#29]
I did a fresh installation of cronkeep with the exception of running with SSL.  I'm not able to edit/delete the default cron job or add a new cron job.  Looking at my browser debug window it looks like the JavaScript is referencing the /job/* directory, which I don't have, giving a 404 error.  I've made sure www-data has full access to the cronkeep directory; including sub directories.  I should also add I'm running this on Raspbian Jessie, which does not use selinux, so I know that's not the issue.

**Comment by bogdanghervan** [comment]
Hey @xeon65, thank you for reporting this.
Did you install CronKeep in a subdirectory? I think you're seeing issue #28. If you create its own vhost (so CronKeep would run from "/"), it should be fine. Let me know, please, if you can make it work this way.

**Comment by xeon65** [comment]
@bogdanghervan, thank you for your reply as well.

I do have it configured to run at the root level:

`<VirtualHost *:443>`
`DocumentRoot /var/www/html/cronkeep/src`

I can create the /job/ directory and browse to the https://foo.bar.com/job/ directory, but it seem the application is referencing some files in those directories that either aren't there or cannot be created.

**Comment by bogdanghervan** [comment]
I would recommend going through this checklist:

1. Make sure Apache's `mod_rewrite` is enabled;
2. Make sure `AllowOverride all` is enabled inside the virtual host definition ([example](https://github.com/cronkeep/cronkeep/blob/master/provision/ubuntu/virtual-host.conf)). This is so that directives in `src/.htaccess` would be taken into account by Apache;
3. Restart Apache;
4. Delete the `/job/` directory you created;

Let me know, please, if these helped in any way.

**Comment by xeon65** [comment]
@bogdanghervan, #2 solved my issue, looks like it was not reading .htaccess due to the settings in the virtual host section of my config.  Thank you very much for your help, all is working!

**Comment by bogdanghervan** [comment]
Good to hear! I will update the docs to make the installation instructions more clear.
